# Generated by Django 6.0.5 on 2026-05-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('name', models.CharField(help_text='Category name', max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('name', models.CharField(help_text='Equipment name', max_length=100, verbose_name='name')),
                ('daily_price', models.PositiveIntegerField(help_text='Equipment daily price', verbose_name='daily price')),
                ('status', models.BooleanField(default=False, help_text='Equipment status', verbose_name='status')),
                ('is_available', models.BooleanField(default=False, help_text='Equipment availability', verbose_name='is available')),
                ('rented', models.BooleanField(default=False, help_text='Equipment rented', verbose_name='rented')),
                ('in_maintenance', models.BooleanField(default=False, help_text='Equipment in maintenance', verbose_name='in maintenance')),
                ('is_lost', models.BooleanField(default=False, help_text='Equipment lost', verbose_name='is lost')),
                ('is_broken', models.BooleanField(default=False, help_text='Equipment broken', verbose_name='is broken')),
                ('image', models.ImageField(blank=True, help_text='Equipment image', null=True, upload_to='equipments/images/', verbose_name='image')),
                ('category', models.ForeignKey(help_text='Equipment category', on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='rental.category')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last modified', verbose_name='Modified At')),
                ('client_name', models.CharField(help_text='Client name', max_length=100, verbose_name='client name')),
                ('client_phone', models.CharField(help_text='Client phone', max_length=15, verbose_name='client phone')),
                ('start_date', models.DateField(help_text='Rent start date', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Rent end date', verbose_name='end date')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Rent total price', max_digits=10, verbose_name='total price')),
                ('rental_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('returned', 'Returned'), ('late_returned', 'Late Returned'), ('lost', 'Lost'), ('broken', 'Broken')], default='pending', help_text='Rental status', max_length=20, verbose_name='rental status')),
                ('equipment', models.ForeignKey(help_text='Rented equipment', on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='rental.equipment')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
